### ISSUE TITLE
Any chance of getting the diyhue custom lights to work?

### ISSUE THREAD

**Issue by pszewello** [marcelveldt/hass_emulated_hue#12]
I use DiyHue, but would love to move the this one, but is there any chance of you supporting the ws2812b lights (https://github.com/diyhue/Lights). Or if I actually use wled controller and pair it with hassio, will it work with entertainment api?

**Comment by marcelveldt** [comment]
This is something I'm investigating. If you use esphome and add the devices to home assistant, it will work out of the box but it's not native entertainment mode (udp).

**Comment by marcelveldt** [comment]
You can use any light that Home Assistant supports and Entertainment mode will work out of the box.
If devices need a special treatment to handle the packetrate of entertainment mode we will look into that later but with the latest version it's already working smooth. I have tested with esphome flashed on my led controllers connected to HA.

Please reopen if you still have questions or run into issues. Thanks!

**Comment by alexyao2015** [comment]
To answer this question, no you will be unable to use the diyhue arduino sketches as those are using a custom protocol that isn't supported by anything but diyhue. You will need to upgrade to esphome as it is much more widely supported and adopted. Unfortunately, the only way to migrate from the diyhue sketches to esphome is to use a serial connection as ota will work due to how the filesystem is setup.

If you previously used the esphome yaml configs from that repository, it would be compatible.
